spring:
  application:
    name: course-dubbo-service
  datasource:
      url: jdbc:mysql://192.168.174.136:3307/db_course?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
thrift:
  user:
    ip: 127.0.0.1
    port: 7911

dubbo:
  application:
    name: course-dubbo-provider
  protocol:
    name: dubbo
    port: 20880
    host: 127.0.0.1
  registry:
    address: zookeeper://192.168.174.136:2181
server:
  port: 9090
